server:
  port: 8888

spring:
  config:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VodianytskyiVI/microservices-config-repo.git
          clone-on-start: true
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: "*"